API_KEY = "api_key"
CONTENT = "content"
EM_CONFIG_FILE = "EMConfig.json"
IMAGE_DIMENSIONS = "imageDimensions"
IMAGE_MODEL = "imageModel"
IMAGE_QUALITY = "imageQuality"
JSON_OBJECT = "json_object"
NUMBER_OF_IMAGES_TO_GENERATE = "numberOfImagesToGenerate"
MESSAGE = "message"
MODEL = "model"
OPEN_AI = "openAi"
ORGANIZATION = "organization"
PROMPT_FILE_NAME = "promptFileName"
RESPONSE_ANSWER_FILE_NAME = "responseAnswerFileName"
ROLE = "role"
TYPE = "type"
USER = "user"



